myshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'


urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

myshop/payment/views.py
import os
import time
from decimal import Decimal

from django.conf import settings
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views.decorators.csrf import csrf_exempt
from orders.models import Order

from .tasks import send_invoice_email
from .wayforpay import WayForPay

wayforpay = WayForPay(key=os.getenv('SECRET_WAYFORPAY_KEY'),
                      domain_name=os.getenv('DOMAIN_NAME'))


def payment_process(request: HttpRequest) -> HttpResponse:
    """
    Handle the payment process for an order.

    This view retrieves the order from the session, creates an invoice using the WayForPay payment
    gateway, and redirects the user to the payment URL.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.

    """
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        invoice_result = wayforpay.create_invoice(
            merchantAccount=os.getenv('WAYFORPAY_MERCHANT_LOGIN'),
            merchantAuthType='SimpleSignature',
            amount=str(order.get_total_cost()),
            currency='UAH',
            productNames=[item.product.name for item in order.items.all()],
            productPrices=[str(item.price) for item in order.items.all()],
            productCounts=[str(item.quantity) for item in order.items.all()]
        )
        order_reference = invoice_result.orderReference

        order.order_reference = order_reference
        order.save()

        if invoice_result and invoice_result.invoiceUrl:
            return redirect(invoice_result.invoiceUrl)
        else:
            return redirect(cancel_url)

    return render(request, 'payment/process.html', {'order': order})


@csrf_exempt
def payment_completed(request: HttpRequest) -> HttpResponse:
    """
    This view processes the payment completion notification from the payment gateway.

    Args:
        request (HttpRequest): The HTTP request object containing POST data from the payment
                               gateway.

    Returns:
        HttpResponse: The HTTP response object.

    """
    data = request.POST

    merchant_signature = data.get('merchantSignature')

    required_fields = [
        'merchantAccount', 'orderReference', 'amount', 'currency', 'authCode',
        'cardPan', 'transactionStatus', 'reasonCode'
    ]
    signature_data = [data[field] for field in required_fields]

    expected_signature = wayforpay.generate_signature(signature_data)

    if merchant_signature == expected_signature:
        order_reference = data.get('orderReference')
        transaction_status = data.get('transactionStatus')

        try:
            order = Order.objects.get(order_reference=order_reference)
            if transaction_status == 'Approved':
                order.paid = True
                order.save()
                send_invoice_email.delay(order.id)
            else:
                order.paid = False
        except Order.DoesNotExist:
            raise "Такого замовлення не існує"

    if order.paid is True:
        return render(request, 'payment/completed.html')
    return render(request, 'payment/canceled.html')


@csrf_exempt
def payment_canceled(request: HttpRequest) -> HttpResponse:
    """
    Handle the payment cancellation.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.

    """
    return render(request, 'payment/canceled.html')

myshop/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block title %}Відміна оплати{% endblock %}

{% block content %}
    <h1>Ваша оплата не була опрацьована.</h1>
    <p>Спробуйте ще раз.</p>
{% endblock %}

myshop/payment/templates/payment/completed.html
{% extends "shop/base.html" %}

{% block title %}Оплата успішна{% endblock %}

{% block content %}
    <h1>Оплата успішна</h1>
    <p>Дякуємо за покупку!</p>
{% endblock %}

myshop/payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Оплата вашого замовлення{% endblock %}

{% block content %}
    <h1>Ваше замовлення</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Вигляд</th>
                <th>Товар</th>
                <th>Ціна</th>
                <th>Кількість</th>
                <th>Сума</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class="row{% cycle "1" "2"%}">
                    <td>
                        <img src="{% if item.product.image %}{{ item.product.image.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}">
                    </td>
                    <td>{{ item.product.name }}</td>
                    <td class="num">{{ item.price }} грн</td>
                    <td class="num">{{ item.quantity }}</td>
                    <td class="num">{{ item.total_price }} грн</td>
                </tr>
            {% endfor %}
            {% if order.coupon %}
                <tr class="subtotal">
                    <td>Стара ціна</td>
                    <td colspan="3"></td>
                    <td class="num">
                        {{ order.get_total_cost_before_discount|floatformat:2 }} грн
                    </td>
                </tr>
                <tr>
                    <td>
                        "{{ order.coupon.code }}" купон
                        (Знижка {{ order.discount }}%)
                    </td>
                <td colspan="3"></td>
                <td class="num neg">
                    - {{ order.get_discount|floatformat:2 }} грн
                </td>
            </tr>
            {% endif %}
            <tr class="total">
                <td>Всього</td>
                <td colspan="3"></td>
                <td class="num">
                    {{ order.get_total_cost|floatformat:2 }} грн
                </td>
            </tr>
        </tbody>
    </table>
    <form action="{% url 'payment:process' %}" method="post">
        <input type="submit" value="Оплатити" class="btn btn-success">
        {% csrf_token %}
    </form>
{% endblock %}